#!/usr/bin/env bash
# Top-level orchestrator: installs elan + Lean toolchain, then comparator,
# lean4export, and landrun at pinned SHAs. Writes a versions.lock at the
# end recording the exact commit each tool was built from.
#
# Idempotent. Safe to re-run. Sources versions.env once.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
# shellcheck source=../versions.env
source "${REPO_ROOT}/versions.env"

echo "==================================================================="
echo "codewars-lean4 runner: preparing toolchain + tools"
echo "  Prefix:    ${CODEWARS_PREFIX}"
echo "  Tools dir: ${CODEWARS_TOOLS_DIR}"
echo "  Bin dir:   ${CODEWARS_BIN_DIR}"
echo "==================================================================="

bash "${SCRIPT_DIR}/install-elan.sh"
bash "${SCRIPT_DIR}/install-comparator.sh"
bash "${SCRIPT_DIR}/install-lean4export.sh"
bash "${SCRIPT_DIR}/install-landrun.sh"

# Record what actually landed on disk.
LOCK="${REPO_ROOT}/versions.lock"
echo ">>> Writing ${LOCK}"
{
    echo "# Auto-generated by scripts/prepare-runner.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# DO NOT EDIT by hand. CI diff-checks this against versions.env."
    echo ""
    echo "LEAN_VERSION=${LEAN_VERSION}"
    echo "LEAN_BUILT=$(lean --version 2>/dev/null | tr -d '\n' || echo 'MISSING')"
    for tool in comparator lean4export landrun; do
        d="${CODEWARS_TOOLS_DIR}/${tool}"
        if [ -d "${d}/.git" ]; then
            sha="$(git -C "${d}" rev-parse HEAD)"
            echo "${tool^^}_BUILT_SHA=${sha}"
        else
            echo "${tool^^}_BUILT_SHA=MISSING"
        fi
    done
} > "${LOCK}"

echo ""
echo "==================================================================="
echo "Done. Run scripts/verify-installation.sh to check it end-to-end."
echo "==================================================================="
